
services:
  backend:
    image: mhmnx/sistem-lamaran-backend:latest # <-- Ganti dengan ini
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - media_volume:/app/media
    expose:
      - 8000
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy

  frontend: # Service ini adalah Nginx yang menyajikan React
    image: namauserdockerhub/sistem-lamaran-frontend:latest # <-- Ganti dengan ini
    volumes:
      - media_volume:/app/media
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  media_volume: