# Generated by Django 5.2.4 on 2025-07-09 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DokumenPelamar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dokumen', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='dokumen/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Formasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_formasi', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('kebutuhan', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PelamarProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('tempat_lahir', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('no_telepon', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lamaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('diajukan', 'Diajukan'), ('verifikasi', 'Verifikasi Berkas'), ('lolos', 'Lolos'), ('tidak_lolos', 'Tidak Lolos')], default='diajukan', max_length=30)),
                ('tanggal_lamar', models.DateTimeField(auto_now_add=True)),
                ('formasi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pelamar_set', to='lamaran.formasi')),
            ],
        ),
    ]
