# Generated by Django 5.2.4 on 2025-07-09 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamaran', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelamarprofile',
            name='alamat',
        ),
        migrations.AddField(
            model_name='pelamarprofile',
            name='alamat_lengkap',
            field=models.TextField(blank=True, help_text='Nama jalan, nomor rumah, RT/RW', null=True),
        ),
        migrations.AddField(
            model_name='pelamarprofile',
            name='desa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pelamarprofile',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='pelamarprofile',
            name='kabupaten',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pelamarprofile',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pelamarprofile',
            name='nik',
            field=models.CharField(blank=True, help_text='Nomor Induk Kependudukan', max_length=16, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pelamarprofile',
            name='pas_foto',
            field=models.ImageField(blank=True, help_text='Digunakan sebagai foto profil', null=True, upload_to='pas_foto/'),
        ),
        migrations.AddField(
            model_name='pelamarprofile',
            name='pendidikan_terakhir',
            field=models.CharField(blank=True, help_text='Contoh: S1 Teknik Komputer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pelamarprofile',
            name='provinsi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pelamarprofile',
            name='nama_lengkap',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='DokumenLamaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surat_lamaran', models.FileField(upload_to='dokumen/surat_lamaran/')),
                ('cv', models.FileField(upload_to='dokumen/cv/', verbose_name='Daftar Riwayat Hidup')),
                ('ijazah', models.FileField(upload_to='dokumen/ijazah/')),
                ('transkrip_nilai', models.FileField(upload_to='dokumen/transkrip/')),
                ('ktp', models.FileField(upload_to='dokumen/ktp/')),
                ('str', models.FileField(blank=True, help_text='Surat Tanda Registrasi (jika ada)', null=True, upload_to='dokumen/str/')),
                ('lamaran', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen', to='lamaran.lamaran')),
            ],
        ),
        migrations.DeleteModel(
            name='DokumenPelamar',
        ),
    ]
