# Generated by Django 5.2.4 on 2025-07-09 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamaran', '0003_remove_pelamarprofile_alamat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disposisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catatan', models.TextField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('jenis', models.CharField(choices=[('otomatis', 'Otomatis'), ('manual', 'Manual')], max_length=10)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lamaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposisi', to='lamaran.lamaran')),
            ],
            options={
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
