# Generated by Django 5.2.4 on 2025-07-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamaran', '0004_disposisi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelamarprofile',
            name='nik',
            field=models.CharField(blank=True, help_text='Nomor Induk Kependudukan', max_length=16, null=True),
        ),
    ]
