# Generated by Django 5.2.4 on 2025-07-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamaran', '0005_alter_pelamarprofile_nik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamaran',
            name='status',
            field=models.CharField(choices=[('diajukan', 'Diajukan'), ('lolos_verifikasi', 'Lolos Verifikasi Berkas'), ('gagal_verifikasi', 'Gagal Verifikasi Berkas'), ('tes_tulis', 'Tes Tulis'), ('wawancara', 'Wawancara'), ('diterima', 'Diterima'), ('ditolak', 'Ditolak')], default='diajukan', max_length=30),
        ),
    ]
