# Generated by Django 5.2.4 on 2025-07-10 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamaran', '0006_alter_lamaran_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NilaiTes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_tes', models.CharField(choices=[('tes_cat', 'Tes CAT'), ('keterampilan', 'Keterampilan'), ('psikotest', 'Psikotest'), ('wawancara', 'Wawancara')], max_length=100)),
                ('nilai', models.FloatField()),
                ('dicatat_pada', models.DateTimeField(auto_now_add=True)),
                ('dicatat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lamaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_tes', to='lamaran.lamaran')),
            ],
        ),
    ]
