# Generated by Django 5.2.4 on 2025-07-11 09:07

import functools
import lamaran.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamaran', '0009_lamaran_keterangan_lamaran_status_kelulusan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumenlamaran',
            name='is_cv_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dokumenlamaran',
            name='is_ijazah_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dokumenlamaran',
            name='is_ktp_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dokumenlamaran',
            name='is_str_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dokumenlamaran',
            name='is_surat_lamaran_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dokumenlamaran',
            name='is_transkrip_nilai_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dokumenlamaran',
            name='cv',
            field=models.FileField(upload_to=functools.partial(lamaran.models.get_upload_path, *(), **{'document_type': 'cv'}), verbose_name='Daftar Riwayat Hidup'),
        ),
        migrations.AlterField(
            model_name='dokumenlamaran',
            name='ijazah',
            field=models.FileField(upload_to=functools.partial(lamaran.models.get_upload_path, *(), **{'document_type': 'ijazah'})),
        ),
        migrations.AlterField(
            model_name='dokumenlamaran',
            name='ktp',
            field=models.FileField(upload_to=functools.partial(lamaran.models.get_upload_path, *(), **{'document_type': 'ktp'})),
        ),
        migrations.AlterField(
            model_name='dokumenlamaran',
            name='str',
            field=models.FileField(blank=True, help_text='Surat Tanda Registrasi (jika ada)', null=True, upload_to=functools.partial(lamaran.models.get_upload_path, *(), **{'document_type': 'str'})),
        ),
        migrations.AlterField(
            model_name='dokumenlamaran',
            name='surat_lamaran',
            field=models.FileField(upload_to=functools.partial(lamaran.models.get_upload_path, *(), **{'document_type': 'surat_lamaran'})),
        ),
        migrations.AlterField(
            model_name='dokumenlamaran',
            name='transkrip_nilai',
            field=models.FileField(upload_to=functools.partial(lamaran.models.get_upload_path, *(), **{'document_type': 'transkrip_nilai'})),
        ),
    ]
