# Generated by Django 5.2.4 on 2025-07-13 09:09

import django.utils.timezone
import functools
import lamaran.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamaran', '0012_alter_dokumenlamaran_cv_alter_dokumenlamaran_ijazah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokumenlamaran',
            name='cv',
            field=models.FileField(upload_to=functools.partial(lamaran.models.get_upload_path, *(), **{'document_type': 'cv'}), verbose_name='Daftar Riwayat Hidup'),
        ),
        migrations.AlterField(
            model_name='dokumenlamaran',
            name='ijazah',
            field=models.FileField(upload_to=functools.partial(lamaran.models.get_upload_path, *(), **{'document_type': 'ijazah'})),
        ),
        migrations.AlterField(
            model_name='dokumenlamaran',
            name='ktp',
            field=models.FileField(upload_to=functools.partial(lamaran.models.get_upload_path, *(), **{'document_type': 'ktp'})),
        ),
        migrations.AlterField(
            model_name='dokumenlamaran',
            name='str',
            field=models.FileField(blank=True, help_text='Surat Tanda Registrasi (jika ada)', null=True, upload_to=functools.partial(lamaran.models.get_upload_path, *(), **{'document_type': 'str'})),
        ),
        migrations.AlterField(
            model_name='dokumenlamaran',
            name='surat_lamaran',
            field=models.FileField(upload_to=functools.partial(lamaran.models.get_upload_path, *(), **{'document_type': 'surat_lamaran'})),
        ),
        migrations.AlterField(
            model_name='dokumenlamaran',
            name='transkrip_nilai',
            field=models.FileField(upload_to=functools.partial(lamaran.models.get_upload_path, *(), **{'document_type': 'transkrip_nilai'})),
        ),
        migrations.AlterField(
            model_name='lamaran',
            name='tanggal_lamar',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
