# Generated by Django 5.2.4 on 2025-07-13 11:07

import functools
import lamaran.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamaran', '0013_alter_dokumenlamaran_cv_alter_dokumenlamaran_ijazah_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanCetak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempat', models.CharField(default='Banjarnegara', max_length=100)),
                ('jabatan', models.CharField(default='Direktur RSUD Hj. Anna Lasmanah', max_length=200)),
                ('nama', models.CharField(max_length=100)),
                ('nip', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='dokumenlamaran',
            name='cv',
            field=models.FileField(upload_to=functools.partial(lamaran.models.get_upload_path, *(), **{'document_type': 'cv'}), verbose_name='Daftar Riwayat Hidup'),
        ),
        migrations.AlterField(
            model_name='dokumenlamaran',
            name='ijazah',
            field=models.FileField(upload_to=functools.partial(lamaran.models.get_upload_path, *(), **{'document_type': 'ijazah'})),
        ),
        migrations.AlterField(
            model_name='dokumenlamaran',
            name='ktp',
            field=models.FileField(upload_to=functools.partial(lamaran.models.get_upload_path, *(), **{'document_type': 'ktp'})),
        ),
        migrations.AlterField(
            model_name='dokumenlamaran',
            name='str',
            field=models.FileField(blank=True, help_text='Surat Tanda Registrasi (jika ada)', null=True, upload_to=functools.partial(lamaran.models.get_upload_path, *(), **{'document_type': 'str'})),
        ),
        migrations.AlterField(
            model_name='dokumenlamaran',
            name='surat_lamaran',
            field=models.FileField(upload_to=functools.partial(lamaran.models.get_upload_path, *(), **{'document_type': 'surat_lamaran'})),
        ),
        migrations.AlterField(
            model_name='dokumenlamaran',
            name='transkrip_nilai',
            field=models.FileField(upload_to=functools.partial(lamaran.models.get_upload_path, *(), **{'document_type': 'transkrip_nilai'})),
        ),
    ]
