# Generated by Django 5.2.4 on 2025-07-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('pelamar', 'Pelamar'), ('verifikator', 'Verifikator'), ('superadmin', 'Superadmin'), ('penilai_wawancara', 'Penilai Wawancara'), ('penilai_keterampilan', 'Penilai Keterampilan')], default='pelamar', max_length=20),
        ),
    ]
